version: '3.4'

services:
  authentication:
    image: ${DOCKER_REGISTRY-}authentication
    build:
      context: .
      dockerfile: Authentication/Dockerfile


  postgres:
    image: debezium/postgres:13-alpine
    container_name: postgres_db
    environment:
        - POSTGRES_DB=fueltrackerdev
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Abcd!234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/db
    #networks:
    #  - FuelTrackerV1


#services:
#    postgres:
#        image: postgres:latest
#        container_name: postgres_db
#        environment:
#          - POSTGRES_USER=fueltracker
#          - POSTGRES_PASSWORD=Abcd!234
#          - POSTGRES_DB=fueltrackerdev
#        ports:
#          - '5432:5432'

 #postgres:
 #   #image: debezium/postgres:13-alpine
 #   image: postgres:latest
 #   container_name: postgres_db
 #   environment:
 #       - POSTGRES_DB=fueltrackerdev
 #       - POSTGRES_USER=fueltracker
 #       - POSTGRES_PASSWORD=Abcd!234
 #   ports:
 #     - "5432:5432"
 #   volumes:
 #     - postgres-data:/data/db
 #   networks:
 #     - fuel-tracker-services


volumes:
  postgres-data:









